---
- name: Ensure user '{{ user_name }}' exists
  user:
    name: "{{ user_name }}"
    comment: "{{ user_name }} User"
    password: "{{ user_password | password_hash('sha512') }}"
    shell: "{{ '/bin/zsh' if (group_names | intersect(['kokos', 'k3d'])) else '/bin/bash' }}"
    state: present
    create_home: yes
    groups: sudo
    append: yes
    update_password: on_create
  when: user_password is defined

- name: Ensure .ssh exists for {{ user_name }}
  file:
    path: /home/{{ user_name }}/.ssh
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0700"
  when: user_password is defined

- name: Add SSH public key for '{{ user_name }}'
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file', user_name ~ '.pub') }}"