---
all:
  children:
    kokos:
      hosts:
        koko:
          ansible_host: 192.168.0.102
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3
        koko-dev:
          ansible_host: 192.168.0.104
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3

    kokopve:
      hosts:
        koko-pve1:
          ansible_host: 192.168.0.100
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3.13
        koko-pve2:
          ansible_host: 192.168.0.101
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3.13

    pbs_servers:
      hosts:
        pbs:
          ansible_host: 192.168.0.103
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3.13

    k3s:
      hosts:
        k3s1:
          ansible_host: 192.168.0.120
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3
        k3s2:
          ansible_host: 192.168.0.121
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3

    k3d:
      hosts:
        k3d1:
          ansible_host: 192.168.0.108
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3
