---
all:
  children:
    koko:
      hosts:
        192.168.0.102:
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3.12

    koko-dev:
      hosts:
        192.168.0.104:
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3.12

    kokopve:
      hosts:
        192.168.0.100:
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3.13
        192.168.0.101:
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3.13

    pbs:
      hosts:
        192.168.0.103:
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3.13
