---
all:
  children:
    kokos:
      hosts:
        koko:
          ansible_host: 192.168.0.102
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3
        koko-dev:
          ansible_host: 192.168.0.104
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3

    kokopve:
      hosts:
        koko-pve1:
          ansible_host: 192.168.0.100
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3.13
        koko-pve2:
          ansible_host: 192.168.0.101
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3.13

    pbs_servers:
      hosts:
        pbs:
          ansible_host: 192.168.0.103
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3.13

    k8s:
      hosts:
        k8s1:
          ansible_host: 192.168.0.110
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3
        k8s2:
          ansible_host: 192.168.0.111
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3
        k8s3:
          ansible_host: 192.168.0.112
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3
        k8s4:
          ansible_host: 192.168.0.113
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3
        k8s5:
          ansible_host: 192.168.0.114
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3

    k3s:
      hosts:
        k3s1:
          ansible_host: 192.168.0.108
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3
