---
all:
  children:
    koko:
      hosts:
        192.168.0.102:
          hostname: koko
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3

    koko-dev:
      hosts:
        192.168.0.104:
          hostname: koko-dev
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3

    kokopve:
      hosts:
        192.168.0.100:
          hostname: koko-pve1
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3.13
        192.168.0.101:
          hostname: koko-pve2
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3.13

    pbs:
      hosts:
        192.168.0.103:
          hostname: pbs
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3.13

    k8s:
      hosts:
        192.168.0.105:
          hostname: k8s-dev
          ansible_user: nahuel
          ansible_python_interpreter: /usr/bin/python3
